### ISSUE TITLE
Error handling in ReferenceFactory when CSL parsing fails

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#102]
E.g. illegal args, anystyle service timeouts or down

**Comment by mdoering** [comment]
@ayco-at-naturalis how does it behave now?any commits?

**Comment by mdoering** [comment]
Anystyle errors bring down the entire import. I don't think this is the desired behavior:


```
Dataset 174 import failed. Log to pg.
--
org.col.admin.task.importer.NormalizationFailedException: Failed to read ACEF files
	at org.col.admin.task.importer.acef.AcefInserter.batchInsert(AcefInserter.java:83)
	at org.col.admin.task.importer.NeoInserter.insertAll(NeoInserter.java:39)
	at org.col.admin.task.importer.Normalizer.insertData(Normalizer.java:591)
	at org.col.admin.task.importer.Normalizer.run(Normalizer.java:68)
	at org.col.admin.task.importer.Normalizer.run(Normalizer.java:55)
	at org.col.admin.task.importer.ImportJob.importDataset(ImportJob.java:111)
	at org.col.admin.task.importer.ImportJob.call(ImportJob.java:71)
	at org.col.admin.task.importer.ImportManager.runImport(ImportManager.java:111)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unexpected response from Anystyle
	at org.col.csl.AnystyleParserWrapper.parse(AnystyleParserWrapper.java:62)
	at org.col.admin.task.importer.reference.ReferenceFactory.parse(ReferenceFactory.java:108)
	at org.col.admin.task.importer.reference.ReferenceFactory.fromACEF(ReferenceFactory.java:68)
	at org.col.admin.task.importer.acef.AcefInserter.lambda$insertReferences$2(AcefInserter.java:142)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.col.admin.task.importer.acef.AcefInserter.insertReferences(AcefInserter.java:140)
	at org.col.admin.task.importer.acef.AcefInserter.batchInsert(AcefInserter.java:63)
	... 13 common frames omitted
```

**Comment by ayco-at-naturalis** [comment]
I am curious what the raw JSON-result was; apparently not a CslData list of size 1. And what the input was.

It's not really an UnparsableException. Anystyle will parse whatever (nonsensical) string you throw at it.

Nevertheless, I'll make AnystyleParserWrapper throw UnparsableExceptions in stead of RuntimeExceptions so we get through the imports

**Comment by ayco-at-naturalis** [comment]
The error (i.e. in the stack trace like above) will now show both input and output

**Comment by mdoering** [comment]
How does anystyle react to line breaks in the input string? Could it consider these as 2 separate citations?

**Comment by mdoering** [comment]
using 2 refs with line break as the input will cause an anystyle error:

http://admin.col.plus/parser/csl?ref=D%C3%B6ring%201999%3A%20Akazien%20im%20Winter.%20Berlin%0AGreuther%2C%20W.%3A%20Reign%20in%20blood.%20Music%20journal%2012(8).%202017


See https://logs.gbif.org/goto/5eda89e423f9b4612668178e648fea31

**Comment by ayco-at-naturalis** [comment]
I fixed this, but all error handling is now in AnystyleParserWrapper (not in the ref factory). The @JsonCreator & @JsonValue methods have been removed again and the only change to the CSLRefType Serde class is that the IllegalArgumentException thrown by enum.valueOf is converted to a JsonMappingException, which was anyhow trapped by the AnystyleParserWrapper

**Comment by mdoering** [comment]
is the code comitted yet? I still see RuntimeException being thrown

**Comment by mdoering** [comment]
here is a real example of multiple citations returned:

```
Error parsing citation: "Bull. Lloyd Libr. 35 (Mycol. Ser. 8)





PUERTO RICO: Mayagüez, 29.XI.1924, Tucker, C. M., wood (BPI 718004 [Lloyd herb.
11992], HOLOTYPE of Kretzschmaria tuckeri) 9 (1936)": Anystyle result is list of size 3 (expected 1).Anystyle response was: [{"author":[{"family":"Libr","given":"Bull Lloyd"}],"note":"35 (Mycol. Ser. 8","id":"libr-a","type":"misc"},{"editor":[],"note":"718004 [Lloyd herb","id":"puerto-a","type":"misc"},{"container-title":"11992], HOLOTYPE of Kretzschmaria tuckeri)","page":"9","language":"","issued":{"date-parts":[[1936]]},"id":"unknown1936a","type":"chapter"}]

```

In any case we need to think how to deal with unparsable citations. Swallowing them is not an option and we should fall back to a manual creation of a reference/CSL in such cases as above. E.g. set the author, year, title and container title from the ACEF fields (or the respective other inputs). All citations must end up as readable references at the end

**Comment by mdoering** [comment]
see here for many more error examples: https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:'2018-05-22T13:35:00.000Z',mode:absolute,to:'2018-05-24T21:59:59.999Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col),query:(match:(environment:(query:col,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!f,type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:logger_name,negate:!f,type:phrase,value:org.col.csl.AnystyleParserWrapper),query:(match:(logger_name:(query:org.col.csl.AnystyleParserWrapper,type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))

**Comment by mdoering** [comment]
Example of an unparsable, persisted reference:
```
{
  "key": 478,
  "id": "Rep-03633",
  "datasetKey": 8,
  "verbatimKey": 35234,
  "csl": {
    
  },
  "issues": Array[1][
    "reference unparsable"
  ]
}
```

This reference is unusable as it doesn't have any data

**Comment by mdoering** [comment]
Solution as discussed:

Reference should have a `citation` field that gets populated by a default style from the CSL just like the int year. Implement this in the `ReferenceFactory.postParse(ref)` method. If the citation is not parsable the whole citation string as passed to Anystyle should be used to populate Reference.citation and the verbatim be flagged with the Unparsable issue.
