### ISSUE TITLE
CoL+ to AG reference table issues

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#393]
Just to help keep track of what still needs to be fixed in the references table export, here's the remaining issues:

- [x] authors column is in JSON
- [x] year column is not populated
- [ ] source column is not populated

**Comment by mdoering** [comment]
This has been fixed in https://github.com/Sp2000/colplus-backend/commit/f288f84f688999e1392a7cce55a346677d7509d8

**Comment by gdower** [comment]
The `references.source` column is still not populated in the latest export I generated a few minutes ago.
